### ISSUE TITLE
main.h

### ISSUE THREAD

**Issue by MBall0u** [MBall0u/atlas-printf#1]
add main.h and add the struct and prototypes to it as we go

**Comment by MBall0u** [comment]
`#ifndef main_h
#define main_h

struct specifier {
char *spec;
void (*f)(va_list);
};

int _printf (const char *format, ...);
int (*get_spec_func(char *s))(va_list args);'

**Comment by HarrisonGearhart** [comment]
created main.h
last line before #endif is " int(*get_spec_func(char *s))(va_list_args);

**Comment by MBall0u** [comment]
I added a typedef to the struct and added betty compliant comments as well

**Comment by MBall0u** [comment]
main.h is all good, added new prototypes as i went but it is good
